package com.example.shoponline.utils.variable

const val HOME_SCREEN = "home_screen"
const val CATEGORIES_SCREEN = "categories_screen"
const val SEARCH_SCREEN = "search_screen"
const val PROFILE_SCREEN = "profile_screen"
const val DETAIL_CATEGORY_SCREEN = "detail_category_screen"
const val DETAIL_CATEGORY_PRODUCT_SCREEN = "detail_category_product"
const val DETAIL_PRODUCT_SCREEN = "detail_product_screen"
const val PROPERTIES_PRODUCT_SCREEN = "properties_product_screen"
const val REVIEW_PRODUCT_SCREEN = "review_product_screen"
const val BOTTOM_SHEET_DETAIL_PRODUCT = "bottom_sheet_detail_product"
const val CHART_SCREEN = "chart_screen"
const val COMPARE_PRODUCT_SCREEN = "compare_product"
const val MAIN_COMPARE_PRODUCT_SCREEN = "main_compare_product"